CREATE DATABASE IF NOT EXISTS xuitter_db;
USE xuitter_db;

CREATE TABLE IF NOT EXISTS publicacoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    texto VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curtida BOOLEAN DEFAULT FALSE
);
